apiVersion: v1
kind: Secret
metadata:
  name: jira-db
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.jiraSecrets.db.username | quote }}
  password: {{ .Values.jiraSecrets.db.password | quote }}
