{{- if .Values.bitbucketSecrets.license }}
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-license
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  license-key: {{ .Values.bitbucketSecrets.license | quote }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-sysadmin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.bitbucketSecrets.admin.username | quote }}
  password: {{ .Values.bitbucketSecrets.admin.password | quote }}
  displayName: {{ .Values.bitbucketSecrets.admin.displayName | quote }}
  emailAddress: {{ .Values.bitbucketSecrets.admin.emailAddress | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-db
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.bitbucketSecrets.db.username | quote }}
  password: {{ .Values.bitbucketSecrets.db.password | quote }}
