apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-shared-home
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.bitbucket.volumes.sharedHome.storageClassName }}
  resources:
    requests:
      storage: 10Gi
