apiVersion: v2
name: jira
description: Jira Data Center umbrella chart for devtools
type: application
version: 1.0.0
appVersion: "9.12.8"
dependencies:
  - name: jira
    version: 1.20.0
    repository: "file://./charts/jira"
