apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    tunnel: {{ .Values.tunnelId }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
{{ toYaml .Values.ingress | indent 6 }}
