apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudflared
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["tunnel", "--no-autoupdate", "--config", "/etc/cloudflared/config/config.yaml", "run"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: credentials
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: cloudflared-credentials
        - name: config
          configMap:
            name: cloudflared-config
