apiVersion: v1
kind: Secret
metadata:
  name: xray-db
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.xraySecrets.db.username | quote }}
  password: {{ .Values.xraySecrets.db.password | quote }}
  url: {{ .Values.xraySecrets.db.url | quote }}
