apiVersion: v2
name: external-secrets-operator
description: External Secrets Operator umbrella chart for devtools
type: application
version: 1.0.0
appVersion: "v2.7.0"
dependencies:
  - name: external-secrets
    version: 2.7.0
    repository: "file://./charts/external-secrets"
