apiVersion: v2
name: bitbucket
description: Bitbucket Data Center 10.2.2
type: application
version: 1.0.0
appVersion: "10.2.2"
dependencies:
  - name: bitbucket
    version: "2.0.13"
    repository: "file://./charts/bitbucket"
