{
 "title": "API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "API_NAME",
    "label": "API Name",
    "query": {
     "query": "label_values(uptime_seconds,app_name)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(uptime_seconds,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime_seconds{app_name=~\"$API_NAME\", namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(starlette_requests_total{ app_name=~\"$API_NAME\", namespace=~\"$Namespace\", path!~\"/healthcheck|/metrics|/openapi.json|/docs|/static\"}) by (method, path, status_code)"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(starlette_requests_in_progress) by (method)"
    }
   ]
  },
  {
   "title": "Request Duration p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate (starlette_request_duration_seconds_bucket{app_name=~\"$API_NAME\", namespace=~\"$Namespace\", path!~\"/healthcheck|/metrics|/openapi.json|/docs|/static\"} [5m])) by (le, method, path, status_code))"
    }
   ]
  }
 ]
}