{{- if and .Values.wrapper.rdsAdmin.usernameSsmParameter .Values.wrapper.rdsAdmin.passwordSsmParameter }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: rds-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.wrapper.rdsAdmin.usernameSsmParameter | quote }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.wrapper.rdsAdmin.passwordSsmParameter | quote }}
{{- end }}
