{{- if .Values.confluenceSecrets.license }}
apiVersion: v1
kind: Secret
metadata:
  name: confluence-license
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  license-key: {{ .Values.confluenceSecrets.license | quote }}
---
{{- else if .Values.confluenceSecrets.licenseSsmParameter }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: confluence-license
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: confluence-license
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: {{ .Values.confluenceSecrets.licenseSsmParameter | quote }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: confluence-db
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.confluenceSecrets.db.username | quote }}
  password: {{ .Values.confluenceSecrets.db.password | quote }}
