{{- if .Values.wrapper.adminPasswordSsmParameter }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.wrapper.adminPasswordSsmParameter | quote }}
{{- end }}
